#!/bin/bash
# Generates `ai_module/.env`, which docker compose reads (env_file) for the sysnav
# containers. The Gemini API key is left blank on purpose - fill it in afterwards,
# or pass it to this script.
#
#   ./docker/create_env.sh                  # write .env with an empty GEMINI_API_KEY
#   ./docker/create_env.sh <API_KEY>        # write .env with the key filled in
#   GEMINI_API_KEY=<key> ./docker/create_env.sh
#   ./docker/create_env.sh --force          # overwrite an existing .env
#
# NOTE: .env is read only when the container is CREATED. If you edit it after the
# container exists, recreate it:
#   docker compose -f docker/compose_gpu.yml up -d --force-recreate sysnav_submission

set -euo pipefail

AI_MODULE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$AI_MODULE_ROOT/.env"

FORCE=0
KEY="${GEMINI_API_KEY:-}"
for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE=1 ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) KEY="$arg" ;;
  esac
done

if [ -e "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  echo "[create_env] $ENV_FILE already exists - not overwriting (use --force)." >&2
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<ENVEOF
# sysnav runtime configuration (generated by docker/create_env.sh)
# Read by docker compose via env_file: for the sysnav services.

# REQUIRED: Google Gemini API key. Without it the pipeline still runs, but the
# LLM candidate-selection step degrades to a confidence/distance-based fallback.
GEMINI_API_KEY=$KEY
GEMINI_MODEL=gemini-3.5-flash

# Model weights baked into the image - do not change unless the image changed.
YOLO_WORLD_WEIGHTS=/home/docker/ai_module/weights/yolov8x-worldv2.pt
SAM2_CHECKPOINT=/home/docker/ai_module/weights/sam2.1_hiera_tiny.pt
SAM2_MODEL_CFG=configs/sam2.1/sam2.1_hiera_t.yaml
ENVEOF
chmod 600 "$ENV_FILE"

echo "[create_env] wrote $ENV_FILE (mode 600)"
if [ -z "$KEY" ]; then
  echo "[create_env] GEMINI_API_KEY is EMPTY - open the file and fill it in:"
  echo "               $ENV_FILE"
fi
